CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO_BARRAS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DOUBLE NOT NULL,
    DESCRICAO VARCHAR(1440) NOT NULL,
    VALIDADE DATE,
    QUANTIDADE INT NOT NULL DEFAULT(0),
    PESO DOUBLE,
    FK_CATEGORIA_ID INT,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_CODBARRAS INT,
    FK_FORNECEDOR_CNPJ VARCHAR(14),
    FOREIGN KEY (FK_PRODUTO_CODBARRAS) REFERENCES PRODUTO(CODIGO_BARRAS),
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ)
);