CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    BATIDA VARCHAR(100) NOT NULL,
    RITMO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    CAPA BLOB NOT NULL,
    QTD_FAIXAS INT NOT NULL,
    FK_ARTISTA_CPF VARCHAR(11),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CAPA BLOB NOT NULL,
    DURACAO TIMESTAMP NOT NULL,
    LETRA VARCHAR(1000) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FK_ALBUM_ID INT,
    FK_GENERO_ID INT,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
);