CREATE DATABASE IF NOT EXISTS BD_REDE_SOCIAL;
USE BD_REDE_SOCIAL;

CREATE TABLE IF NOT EXISTS USUARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(500) NOT NULL,
    BIO VARCHAR(150),
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS PUBLICACOES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FOTO BLOB NOT NULL,
    DESCRICAO VARCHAR(1440),
    DATA_PUBLICACAO DATE NOT NULL,
    FK_USUARIO_ID INT,
    FOREIGN KEY (FK_USUARIO_ID) REFERENCES USUARIOS(ID)
);

# Adicionar campo TELEFONE na tabela de USUARIOS
ALTER TABLE USUARIOS
ADD COLUMN TELEFONE VARCHAR(9) NOT NULL;

# Alterar um tamanho/tipo de um campo
ALTER TABLE USUARIOS
MODIFY COLUMN BIO VARCHAR(500);

# Remover coluna
ALTER TABLE USUARIOS
DROP CPF;

#Renomear um campo
ALTER TABLE PUBLICACOES
RENAME COLUMN DESCRICAO TO LEGENDA;

ALTER TABLE PUBLICACOES
CHANGE COLUMN DESCRICAO LEGENDA VARCHAR(1440);

# Excluir uma TABELA INTEIRA
DROP TABLE PUBLICACOES;

# Excluir o banco de dados
DROP DATABASE BD_REDE_SOCIAL;